### PR TITLE
PLF-6568 : create DocumentBuilderFactory only once

### PR DESCRIPTION
**Pull request by thomasdelhomenie**

### CODE REVIEW

**Comment by trongtt** [comment]
Great to have this applied in gatein-portal.

BTW, do you think we could even create only one default **DocumentBuilder docBuilder = documentBuilderFactory.newDocumentBuilder();** for whole PLF ?

**Comment by thomasdelhomenie** [comment]
Not sure it is a good idea to have one DocumentBuilderFactory for the whole PLF because it is not always used with the same attributes : https://github.com/exodev/gatein-portal/blob/develop/component/common/src/main/java/org/exoplatform/commons/xml/XMLValidator.java#L74-L77
It would require to set it before each use and it is quite expensive. Except if we are able to use the same attributes in all cases, which is not the case today. WDYT ?

Also, I see in https://jira.exoplatform.org/browse/ECMS-7407 that we create not only the DocumentBuilderFactory once, but also the DocumentBuilder. According to the Javadoc it is not clear if DocumentBuilder is thread-safe but since it has a reset method it tends to make me think it holds a state and thus cannot be used safely in concurrence. Maybe the good solution if we want to reuse DocumentBuilder is to put them in a ThreadLocal and call the reset method after each use.
WDYT ?

**Comment by trongtt** [comment]
I just meant we create only one for a default DocumentBuilderFactory without setting attributes. Of course, it will need to be documented clearly that setting attributes are not allowed in this instance.

Yes, it is not clear if DocumentBuilder is thread-safe. BUT for me, it will not be a problem in this case we use it to create newDocument() only.
Definitely we can make some unit tests or even a real performance multiple threading test for that.
WDYT ?

**Comment by thomasdelhomenie** [comment]
For DocumentBuilderFactory you mean we provide a default instance without setting any attributes, that can be used anywhere in the platform, and if a process needs to set some specific attributes, it creates a new DocumentBuilderFactory ?

Concerning DocumentBuilder, it is mainly used to parse document, like here https://github.com/exoplatform/gatein-portal/blob/develop/component/common/src/main/java/org/exoplatform/commons/xml/XMLValidator.java#L85 or https://github.com/exoplatform/gatein-portal/blob/develop/component/resources/src/main/java/org/exoplatform/services/resources/XMLResourceBundleParser.java#L145. And this thread tends to confirm it is a bad idea to use only one instance with multiple threads to parse documents : http://stackoverflow.com/a/12455887

**Comment by trongtt** [comment]
yes, create a new DocumentBuilderFactory if we need to set some specific attributes.

we can not clearly use the single DocumentBuilder with multiple threads to parse documents.
So, the only DocumentBuilder will not be able for getting (private in a class), and just be used to create newDocument() via a static method like #buildNewDocument(). WDYT ?

**Comment by thomasdelhomenie** [comment]
For DocumentBuilderFactory, don't you think it can be dangerous ? I mean, if an application gets this unique instance and set attributes, it will be shared by all others  applications.

For DocumentBuilder, yes we could implement a #buildNewDocument(). We just have to check if we already use the newDocument method somewhere :)
And what about the idea to put DocumentBuilder instance in a ThreadLocal and reset it after its use ?

**Comment by trongtt** [comment]
For DocumentBuilderFactory, yes it's dangerous and that's why we should document it clearly that "setting attributes are not allowed in this instance." as I said. Or maybe we should scope it somehow for internal use in PLF projects.

The idea of putting DocumentBuilder instance in a ThreadLocal and reset it after its use would be good too :)

**Comment by thomasdelhomenie** [comment]
I am still not sure about having one unique DocumentBuilderFactory for the whole platform. As we said it can be dangerous if misused (we can add documentation, but it is only documentation...), and moreover it does not prevent from creating new instances.

I propose to apply this PR as a first step of optimisation. Is that ok for you ?

**Comment by trongtt** [comment]
YES, no problem at all.

**Pull request merged**
