### PR TITLE
PLF-8250 : enable CSRF protection by default on WebUI actions

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
The WebUI framework provide a protection against CSRF attack, but this protection is not enabled by default and was not enabled on most of the actions.
This leads to have some actions exposed to CSRF attacks as the one described in the issue (site deletion).

This fix enables the CSRF protection by default and disables it when required.
It means that all actions are now protected by default. This has the following advantages:
* we must explicitly disable the protection, so it is only done in specific cases and on purpose
* no need to go through all the actions and enable it when required (error-prone)

It also has drawbacks:
* all actions are protected, including some which do not expose security issues (no data update)
* the check on CSRF token is done on almost all actions know, so there is a (very) little overhead

To be noted: CSRF protection has been disabled on actions called through the JS API eXo.env.server.createPortalURL since it does not send the CSRF token.

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
I am not sure to understand the issue. Is the issue you described due to the change on this PR ?

**Comment by trongtt** [comment]
> I am not sure to understand the issue. Is the issue you described due to the change on this PR ?

Yes, it's due to this PR that now CSRF protection is enable by default (inclusive rendering ajax requests). In the case it detects a CSRF request (it's also the case of session timeout), the response will be empty with status code 200 and nothing happens in client side. So we should improve it somehow to warn users about the error I think.

**Comment by thomasdelhomenie** [comment]
Ah yes. Actually that was also the case before this PR, but it happened in fewer cases since the csrf check was enabled on less actions. This PR did not change this behavior, it just enabled it on more actions.
Since we already run the non-regression tests, I propose to merge this PR as is and to open an issue to work on the improvement you described. WDYT ?

**Comment by trongtt** [comment]
Yes, I agree. That's why I still approved the PR and just raise this concern to see if we should address it in here or not.

**Pull request merged**
