### PR TITLE
[EXOGTN-2209] fix JS modules multiple loads in dev mode

### PR DESCRIPTION
**Pull request by MrHanachoo**

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
LGTM, but please add unit tests.

**Comment by trongtt** [comment]
It was a typo mistake I think and the fix is good to care about the possibility of memory leak. Unfortunately it also disables the capability of live JS update in dev mode.

So I just updated the PR to not use cache in dev mode. @MrHanachoo please re-validate it.

**Comment by MrHanachoo** [comment]
@thomasdelhomenie unit test added.
@trongtt LGTM, we might need unit test for this change.

**Comment by trongtt** [comment]
@MrHanachoo the change is about switch check condition at runtime. So not necessary to do integration test here I think.

So PR looks good now.

**Comment by MrHanachoo** [comment]
Merged.

**Pull request closed without merging**
